pipeline {
    agent any
    stages {
        stage('Build') {
        parallel {
            stage('Build') {
            steps {
                sh 'rm -rf ./devops'
                dir('devops') {
                    sh 'python3 -m pip install -r requirements.txt'
                }
            }
            }
        }
        }

        stage('Test') {
        steps {
            dir('devops') {
                sh 'python3 -m unittest'
            }
        }
        }

        stage('Deploy')
        {
            steps {
                dir('devops') {
                            sh " python3 app.py & disown"
                        }
            }
        }
    }

    post {
            always {
                echo 'The pipeline completed'
            }
            success {
                echo "Flask Application Up and running!!"
            }
            failure {
                echo 'Build stage failed'
                error('Stopping early…')
            }
        }
}